### ISSUE TITLE
There's no "motivation" for players to quickly end up the round

### ISSUE THREAD

**Issue by martin-macak** [odanek/duel6r#10]
Sometimes there are just two players on the map and they are evading themselves. This sucks ass because the others have to wait for them.
It would be nice if there was some kind of motivation or/else some mechanism, which would force the players to engage in close combat.
IE inner blocks can disappear making all the players to fall at the bottom of the screen, so they will have to settle things down. Or some suicidal counter. I don't know.

**Comment by odanek** [comment]
This has been addressed by raising the water level when there are last two players remaining.
