### ISSUE TITLE
Allow shot collision

### ISSUE THREAD

**Issue by odanek** [odanek/duel6r#38]
Allow two shots to collide. This would be configurable so that for example bazooka shots will be able to collide with other shots but pistol bullets won't.

**Comment by odanek** [comment]
Implemented in 7dfb93f7d871369a463862b446ad618a4ef98106

**Comment by plesatejvlk** [comment]
Uuuu, tak to musim zkusit!:D

On Sunday, 19 June 2016, Ondřej Daněk <notifications@github.com> wrote:

> Implemented in 7dfb93f
> <https://github.com/odanek/duel6r/commit/7dfb93f7d871369a463862b446ad618a4ef98106>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/odanek/duel6r/issues/38#issuecomment-227012527>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFDp3uszNYE-Xnj87zIdpykQtAYFPzp0ks5qNYoKgaJpZM4EOsk5>
> .
>


-- 
http://honza.kotrs.cz
