### ISSUE TITLE
Create a "no-start" piece for map editor

### ISSUE THREAD

**Issue by plesatejvlk** [odanek/duel6r#75]
To prevent unnecessary early deaths because of unfortunate starting position I would suggest to:
- add a piece to map editor to mark a place for "no-start"
- make starting routine respect such place and prevent placing a player there (unless necessary)

**Comment by odanek** [comment]
I have instead implemented a simpler solution in 9223943dbc4a6d1d10dc728159e807f1e5adec5c that makes sure that all players start on a visible position, i.e., on a solid ground and not behind a waterfall or a pillar/tree/etc.

**Comment by plesatejvlk** [comment]
Awesome!:)
